#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will Check Remote Server Connectivity

hosts="/home/salah/scripts/myhosts"

for ip in $(cat $hosts)
do
	ping -c1 $ip &> /dev/null
		if [ $? -eq 0 ]
		then
			echo $ip is Ok
		else
			echo $ip is Not Ok
		fi
done 
