#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will do

echo how many files do you want?
read i
echo
echo please inter the start namee of the files?
read n

for s in  $(seq 1 $i)
	do
		touch $n.$s 
	done 
