#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will do
echo
 
ls -l /home/salah/scripts/check

if [ $? -eq 0 ]
	then 
	echo File exist
else
	echo File does not exist
fi

echo
echo End of script 
