#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will do for loop

echo
for i in 1 2 3 4 5
do
	echo "Welcome $i times"
done 
