#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will Handel the error in a massage.txt

grep -i error /var/log/syslog > /home/salah/scripts/massage


 
