#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will handel warn to a massage file

grep -i warn /home/salah/scripts/massage > /home/salah/scripts/output 
