#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will list of users logged in by date

today=`date | awk '{print $1,$2,$3}'` 
last | grep "$today"

echo 

# Description    : This script will list of users logged in by user input
echo

echo "Please enter day {e.g. Mon}"
read d
echo
echo "Please enter month {e.g. Aug}"
read m
echo
echo "please enter date {e.g. 28}"
read da
echo

last | grep "$d $m $da"

