#!/bin/bash
# Author         : Salah Khaled
# Date Created   : 12/25/2018
# Date Modified  : 12/25/2018
# Description    : This script will do

for i in {1..10}
	do 
		echo $i
		sleep 1
	done
echo End Of Script	 
